---
- name: Add the OS specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Install OS specific packages
  include: "install_{{ ansible_os_family }}.yml"

- include: configure.yml
